export const CLEAR_LOADING = "CLEAR_LOADING";
export const START_LOADING = "START_LOADING";

export const RECEIVE_BIKE_STATIONS = "RECEIVE_BIKE_STATIONS";
export const RECEIVE_CYCLE_WAYS = "RECEIVE_CYCLE_WAYS";
export const RECEIVE_AREAS = "RECEIVE_AREAS";
export const RECEIVE_BIKE_STATIONS_AND_CYCLE_WAYS = "RECEIVE_BIKE_STATIONS_AND_CYCLE_WAYS";

export const RESET_STATIONS = "RESET_STATIONS";
export const RESET_WAYS = "RESET_WAYS";
export const RESET_AREAS = "RESET_AREAS";